---
anchors:
  thresholds-operstate: &thresholds-operstate
    - color: "#FF3154" # red
      level: 0
    - color: "#4BDD33" # green
      level: 1

cellIdPreamble: cell-
cells:
  sspine1_e1:
    dataRef: oper-state:superspine1:ethernet-1/1
    fillColor:
      thresholds: *thresholds-operstate
  sspine1_e2:
    dataRef: oper-state:superspine1:ethernet-1/2
    fillColor:
      thresholds: *thresholds-operstate
  sspine1_e3:
    dataRef: oper-state:superspine1:ethernet-1/3
    fillColor:
      thresholds: *thresholds-operstate
  sspine1_back:
    dataRef: oper-state:superspine1
    fillColor:
      thresholds: *thresholds-operstate



